#!/usr/bin/env bash
### end common-components/bash-shebang

# Welcome to the codica laptop script! Be prepared to turn your laptop (or
# desktop, no haters here) into an awesome development machine.

RED='\033[0;32m'
NC='\033[0m'

fancy_echo() {
  local fmt="$1"; shift
  printf "\\n${RED}$fmt${NC}\\n" "$@"1
}

read -p "Enter your email to generate ssh key: " email

fancy_echo "Installing curl ..."
  sudo apt install -y curl

fancy_echo "Installing git, for source control management ..."
  sudo apt install -y git

fancy_echo "Installing zsh and making it default shell..."
  sudo apt install -y zsh
  chsh -s $(which zsh) # Require log-out

fancy_echo "Installing oh-my-zsh ..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

fancy_echo "Installing libraries for common gem dependencies ..."
  sudo apt --ignore-missing install -y libxslt1-dev libcurl4-openssl-dev libssl-dev libksba8 libksba-dev libreadline-dev build-essential apt-transport-https ca-certificates gnupg-agent software-properties-common libgdbm-dev libffi-dev zlib1g-dev autoconf bison libyaml-dev libpq-dev

fancy_echo "Installing asdf ..."
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
  asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
  sudo apt install libbz2-dev libsqlite3-dev liblzma-dev
  asdf plugin add python
  echo '. "$HOME/.asdf/asdf.sh"' >> ~/.zshrc

fancy_echo "Installing snapd canonical package manager"
  sudo apt install -y snapd
  sudo mv /etc/ld.so.preload /etc/ld.so.preload.org

fancy_echo "Installing Postman"
  sudo snap install postman

fancy_echo "Installing Insomnia"
  sudo snap install insomnia

fancy_echo "Installing sqlite3, for prototyping database-backed rails apps ..."
 sudo apt install -y libsqlite3-dev sqlite3

fancy_echo "Installing PostgreSQL 15, a good open source relational database ..."
  sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
  sudo apt update
  sudo apt install -y postgresql-15

fancy_echo "Installing tmux, to save project state and switch between projects ..."
  sudo apt install -y tmux

fancy_echo "Installing guake, a super terminal"
  sudo apt install -y guake

fancy_echo "Installing ImageMagick, to crop and resize images ..."
  sudo apt install -y imagemagick libmagickwand-dev

fancy_echo "Installing Redis ..."
  sudo snap install redis
  sudo snap alias redis.cli redis-cli

fancy_echo "Installing Ngrok ..."
  sudo snap install ngrok

fancy_echo "Installing Sublime Text 3 ..."
  sudo snap install --classic sublime-text

fancy_echo "Installing VS Code ..."
  sudo snap install --classic code

fancy_echo "Installing Heroku CLI client ..."
  curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

fancy_echo "Installing Heroku plugins ..."
  heroku plugins:install heroku-accounts
  heroku plugins:install heroku-builds
  heroku plugins:install heroku-config
  heroku plugins:install data-maintenance

fancy_echo "Installing Flameshot ..."
  sudo apt install flameshot

fancy_echo "Installing TablePlus ..."
  wget -qO - https://deb.tableplus.com/apt.tableplus.com.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tableplus-archive.gpg > /dev/null
  sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian/22 tableplus main"
  sudo apt update
  sudo apt install tableplus

fancy_echo "Installing OpenSSH Server ..."
  sudo apt install openssh-server

fancy_echo "Installing btop ..."
  sudo snap install btop

fancy_echo "Installing alacritty ..."
  sudo add-apt-repository ppa:aslatter/ppa -y
  sudo apt install alacritty

if [ -f "$HOME/.laptop-ubuntu.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop-ubuntu.local ..."
  . "$HOME/.laptop-ubuntu.local"
fi
